<a href="https://colab.research.google.com/github/Ahmed-ali-fcai-811/machine-learning/blob/main/logisticRegressionAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from keras.datasets import mnist
import numpy as np

In [ ]:
(x_train , y_train) , (x_test , y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
# 0 - 1 mask 
train_data_msk  = np.where((y_train==1) | (y_train == 0))
test_data_msk = np.where( (y_test == 1) | (y_test == 0))

In [ ]:
x_train = x_train[train_data_msk]
y_train = y_train[train_data_msk]

In [ ]:
x_test = x_test[test_data_msk]
y_test = y_test[test_data_msk]

In [ ]:
x_train = x_train.reshape(x_train.shape[0] ,-1 )

In [ ]:
x_train.shape

(12665, 784)

In [ ]:
x_test = x_test.reshape(x_test.shape[0] ,-1 )

In [ ]:
y_test.shape

(2115,)

In [ ]:
x_train = (x_train - np.mean(x_train)) / np.std(x_train)
x_test = (x_test - np.mean(x_test)) / np.std(x_test)

In [ ]:
class LogisticRegression:
  def __init__(self , eta , n_iters):
    self.eta = eta 
    self.n_iters = n_iters

  def segmoid(self , z):
    return 1/(1+np.exp(-z))

  def predict(self , x):
    output = np.dot(self.w.T , x.T )+self.b
    pred = self.segmoid(output)
    pred = np.where(pred >= 0.5 ,1  , 0)
    return pred


  def fit(self , x , y):
    n_samples , n_features = x.shape
    self.w = np.zeros((n_features , ))
    self.b = 0 

    for i in range(self.n_iters):
      y_pred = self.predict(x)
      c = (y_pred - y)
      dj_dw = (1/n_samples) * np.dot(x.T , c)
      dj_db = (1/n_samples) * np.sum(c)

      self.w -= self.eta * dj_dw
      self.b -= self.eta * dj_db

    return self.w , self.b


In [ ]:
model =  LogisticRegression(0.001 , 1000)

In [ ]:
model.fit(x_train , y_train)
y_pred_test = model.predict(x_test)

In [ ]:
y_pred_test


array([1, 0, 1, ..., 1, 0, 1])

In [ ]:
def accuarcy(y_pred , y):
  acc = 0 
  for i in range (y_pred.shape[0]):
    acc+=(y_pred[i] == y[i])

  return( acc/y_pred.shape[0])*100

In [ ]:
print(accuarcy(y_pred_test , y_test))

99.95271867612293


In [ ]:
ind = np.arange(5)
ind


array([0, 1, 2, 3, 4])

In [ ]:

n = x_train.shape[0]
ind = np.arange(n)
ind

array([    0,     1,     2, ..., 12662, 12663, 12664])

In [ ]:
start = 5
end = 10
train_ind = ind[start:end]
x = x_train[train_ind]
test_ind = np.concatenate((ind[:start] , ind[end:]))
test_ind[5]

10

In [ ]:
def k_fold_validation(x , y , k):
  n_samples = x.shape[0]
  ind = np.arange(n_samples)
  np.random.shuffle(ind)
  segment = n_samples // k
  folds = []
  for i in range (k):
    start = i*segment
    end = (i+1)*segment
    test_ind = ind[start:end]
    train_ind = np.concatenate((ind[:start] , ind[end:]))
    x_test = x[test_ind]
    y_test = y[test_ind]
    x_train = x[train_ind]
    y_train = y[train_ind]
    folds.append((x_train,y_train,x_test,y_test))
  return folds

In [ ]:
folds = k_fold_validation(x_train , y_train , 10)

In [ ]:
len(folds)

10

In [ ]:
rates = [0.1 , 0.01 , 0.001 , 0.0001 , 1 , 0.00000000001]


In [ ]:
def classifier(folds):
  i=1
  for data in folds :
     x_train , y_train , x_test , y_test = data
     print(f"fold number {i}")
     i+=1
     for rate in rates:
       print(f"learning rate = {rate}")
       model = LogisticRegression(rate , 1000)
       model.fit(x_train , y_train)
       y_pred = model.predict(x_test)
       acc = accuarcy(y_pred , y_test)
       print(f"accuarcy = {acc}")
       print("")


In [ ]:
classifier(folds)

fold number 1
learning rate = 0.1
accuarcy = 100.0

learning rate = 0.01
accuarcy = 100.0

learning rate = 0.001
accuarcy = 100.0

learning rate = 0.0001
accuarcy = 100.0

learning rate = 1
accuarcy = 100.0

learning rate = 1e-11
accuarcy = 100.0

fold number 2
learning rate = 0.1
accuarcy = 99.92101105845181

learning rate = 0.01
accuarcy = 99.92101105845181

learning rate = 0.001
accuarcy = 99.92101105845181

learning rate = 0.0001
accuarcy = 99.92101105845181

learning rate = 1
accuarcy = 99.92101105845181

learning rate = 1e-11
accuarcy = 99.92101105845181

fold number 3
learning rate = 0.1
accuarcy = 99.84202211690362

learning rate = 0.01
accuarcy = 99.84202211690362

learning rate = 0.001
accuarcy = 99.84202211690362

learning rate = 0.0001
accuarcy = 99.84202211690362

learning rate = 1
accuarcy = 99.84202211690362

learning rate = 1e-11
accuarcy = 99.84202211690362

fold number 4
learning rate = 0.1
accuarcy = 99.92101105845181

learning rate = 0.01
accuarcy = 99.9210110584518